// 100 architectures, written as data.
//
// Each row is `[id, name, category, rps, p99ms, availability, costUsd, nodes,
// edges, about]`. The two string fields are a deliberately tiny notation —
// `kind:label*replicas`, and `a>b>c` chains — because a hundred architectures
// written as object literals is a file nobody proofreads, and an unproofread
// template is worse than no template: it teaches the wrong shape.
//
// The numbers are targets, not predictions. Each template ships the SLOs a team
// running that system would actually set, and the simulator is then free to
// disagree — several of these fail their own budget at the stated load, which is
// the honest outcome and the reason they are worth opening.

export const CATEGORIES = [
  'Web & API',
  'Commerce & payments',
  'Social & media',
  'Data & analytics',
  'AI & ML',
  'Streaming & events',
  'Platform & infrastructure',
  'Finance & regulated',
  'IoT, mobility & realtime',
  'Enterprise & integration',
]

export const SPECS = [
  /* ── Web & API ─────────────────────────────────────────────────────────── */
  ['url-shortener', 'URL shortener', 'Web & API', 12000, 400, 0.995, 200000,
    'client:users, cdn:edge-cache, lb:edge, app:api*2, cache:hot, nosql:links',
    'users>edge-cache>edge>api>hot>links',
    'Reads outnumber writes about a hundred to one, so the whole design is a cache-hit-rate argument. Take the cache out and watch the key-value store become the system.'],
  ['blog-cms', 'Content site with a CMS', 'Web & API', 3000, 200, 0.995, 50000,
    'client:readers, cdn:cdn, lb:edge, web:render, cache:page-cache, sql:content, blob:media',
    'readers>cdn>edge>render>page-cache>content; render>media',
    'A render tier behind a CDN. The interesting failure is a cold CDN after a purge, when every request reaches the renderer at once.'],
  ['saas-multitenant', 'Multi-tenant SaaS', 'Web & API', 6000, 500, 0.995, 40000,
    'client:tenants, lb:edge, gateway:api-gw, tenant:router, app:core*5, cache:tenant-cache, sql:primary, nosql:tenant-meta',
    'tenants>edge>api-gw>router>core>tenant-cache>primary; router>tenant-meta',
    'One noisy tenant is the whole risk model. The router is where isolation is either enforced or quietly not.'],
  ['rest-api-crud', 'Plain REST API', 'Web & API', 4000, 400, 0.9995, 1500,
    'client:clients, lb:edge, app:api*7, sql:db*3',
    'clients>edge>api>db',
    'The smallest thing worth gating. Useful as a control: change one number and see exactly which SLO moves.'],
  ['graphql-federation', 'Federated GraphQL', 'Web & API', 5000, 400, 0.995, 5000,
    'client:apps, lb:edge, graphql:router*3, micro:users-svc*2, micro:orders-svc*2, micro:catalog-svc*2, cache:query-cache, sql:users-db*2, sql:orders-db*2, nosql:catalog-db',
    'apps>edge>router>users-svc>users-db; router>orders-svc>orders-db; router>catalog-svc>query-cache>catalog-db',
    'One query fans out to three subgraphs, so tail latency is the max of three tails, not the mean. This is the template that makes that visible.'],
  ['static-site-cdn', 'Static site on a CDN', 'Web & API', 8000, 150, 0.995, 150000,
    'client:visitors, dns:dns, cdn:cdn, blob:origin',
    'visitors>dns>cdn>origin',
    'Almost nothing to break, which is the point — it sets the floor other web templates are measured against.'],
  ['search-service', 'Site search', 'Web & API', 4000, 1000, 0.995, 5000,
    'client:users, lb:edge, app:search-api*7, cache:suggest-cache, search:index, queue:index-updates, worker:indexer*7, sql:source-of-truth',
    'users>edge>search-api>suggest-cache>index; search-api>index-updates>indexer>index; indexer>source-of-truth',
    'Query path and index path share one cluster. The failure everyone hits is a reindex storm making queries slow at exactly the wrong moment.'],
  ['auth-service', 'Authentication service', 'Web & API', 9000, 500, 0.995, 30000,
    'client:apps, lb:edge, gateway:api-gw, app:authn*14, cache:session-cache, sql:identity, sign:jwt',
    'apps>edge>api-gw>authn>session-cache>identity; authn>jwt',
    'Everything else depends on it, so its availability target is a tier above the systems it serves. Model an outage here and the blast radius is the whole estate.'],
  ['rate-limited-api', 'Rate-limited public API', 'Web & API', 15000, 500, 0.995, 60000,
    'client:developers, lb:edge, ratelimiter:limiter, gateway:api-gw, app:api*24, cache:quota-cache, nosql:usage',
    'developers>edge>limiter>api-gw>api>quota-cache>usage',
    'The limiter is on the request path, so it is also a dependency. Kill it and decide whether the API fails open or closed — the model prices both.'],
  ['bff-mobile-web', 'BFF for mobile and web', 'Web & API', 7000, 400, 0.995, 2000,
    'client:mobile, client:browser, lb:edge, bff:mobile-bff*2, bff:web-bff*2, micro:profile*2, micro:content*6, cache:shared-cache, sql:core-db*2',
    'mobile>edge>mobile-bff>profile>core-db; browser>edge>web-bff>content>shared-cache>core-db; mobile-bff>content',
    'Two façades over one set of services. Duplicated per-client logic is the cost; a chatty mobile client is the reason.'],

  /* ── Commerce & payments ───────────────────────────────────────────────── */
  ['ecommerce-storefront', 'E-commerce storefront', 'Commerce & payments', 9000, 400, 0.99, 150000,
    'client:shoppers, cdn:cdn, lb:edge, gateway:api-gw, app:storefront, micro:catalog, micro:cart, cache:product-cache, search:product-search, sql:orders, nosql:sessions, blob:images',
    'shoppers>cdn>edge>api-gw>storefront>catalog>product-cache>orders; storefront>cart>sessions; catalog>product-search; cdn>images',
    'The full front of a shop. Black Friday is a scenario, not a hypothetical — run it at four times the load and see what gives first.'],
  ['checkout-flow', 'Checkout', 'Commerce & payments', 2000, 800, 0.995, 10000,
    'client:shoppers, lb:edge, gateway:api-gw, app:checkout*4, micro:pricing, micro:inventory, ledger:ledger*2, queue:order-events, worker:fulfilment*2, sql:orders',
    'shoppers>edge>api-gw>checkout>pricing; checkout>inventory; checkout>ledger>orders; checkout>order-events>fulfilment>orders',
    'Low traffic, extreme consequence. Every component here is on the path between a customer intending to pay and money moving.'],
  ['inventory-service', 'Inventory and stock', 'Commerce & payments', 5000, 1500, 0.995, 2500,
    'client:services, lb:edge, app:inventory*8, cache:stock-cache, sql:stock*2, kafka:stock-events, worker:reconciler*8',
    'services>edge>inventory>stock-cache>stock; inventory>stock-events>reconciler>stock',
    'Overselling is a consistency bug with a refund attached. The cache in front of stock is exactly where that bug lives.'],
  ['cart-service', 'Shopping cart', 'Commerce & payments', 8000, 400, 0.995, 8000,
    'client:shoppers, lb:edge, app:cart*13, cache:cart-cache, nosql:carts',
    'shoppers>edge>cart>cart-cache>carts',
    'A cart is a session with money attached. Losing one is not an outage but it is a lost order, which is why the store behind the cache matters.'],
  ['payment-gateway', 'Payment gateway', 'Commerce & payments', 1500, 2000, 0.99, 80000,
    'client:merchants, lb:edge, gateway:api-gw, app:payments*3, hsm:hsm, ledger:ledger, queue:settlement, worker:settle*2, sql:txn-db, partner:acquirer',
    'merchants>edge>api-gw>payments>hsm; payments>ledger>txn-db; payments>acquirer; payments>settlement>settle>txn-db',
    'The acquirer is someone else\'s system and it is on your critical path. That dependency is the whole availability story.'],
  ['subscription-billing', 'Subscription billing', 'Commerce & payments', 800, 250, 0.999, 1000,
    'client:customers, lb:edge, app:billing-api*2, scheduler:cron, queue:invoice-jobs, worker:invoicer, billing:rating, ledger:ledger, sql:billing-db, push:email',
    'customers>edge>billing-api>billing-db; cron>invoice-jobs>invoicer>rating>ledger>billing-db; invoicer>email',
    'Almost all the work happens on the first of the month. Size it for the average and the monthly run never finishes.'],
  ['order-fulfilment', 'Order fulfilment', 'Commerce & payments', 1200, 4000, 0.99, 50000,
    'client:orders-in, queue:order-queue, worker:picker*4, worker:shipper*2, micro:warehouse, sql:fulfilment-db, push:notify, partner:carrier',
    'orders-in>order-queue>picker>warehouse>fulfilment-db; picker>shipper>carrier; shipper>notify',
    'A pipeline where every stage can fail independently and nothing may be lost. The dead-letter path is not optional here.'],
  ['marketplace', 'Two-sided marketplace', 'Commerce & payments', 6000, 800, 0.995, 25000,
    'client:buyers, client:sellers, lb:edge, gateway:api-gw, app:buyer-app*5, app:seller-app*5, micro:listings*5, micro:payouts*2, search:listing-search, cache:listing-cache, sql:core-db, blob:listing-media, ledger:ledger*3',
    'buyers>edge>api-gw>buyer-app>listings>listing-cache>core-db; listings>listing-search; sellers>edge>api-gw>seller-app>listings; seller-app>payouts>ledger>core-db; seller-app>listing-media',
    'Two user populations with different load shapes on one core. Sellers are few and write-heavy; buyers are many and read-heavy.'],
  ['pricing-engine', 'Dynamic pricing', 'Commerce & payments', 10000, 1500, 0.995, 20000,
    'client:storefront, lb:edge, app:pricing*16, cache:price-cache, featurestore:features, ml:price-model*21, nosql:rules, kafka:price-events',
    'storefront>edge>pricing>price-cache>rules; pricing>features>price-model; pricing>price-events',
    'A model call on the hot path with a 120ms budget. Either the cache carries it or the model has to be smaller.'],
  ['refunds-disputes', 'Refunds and disputes', 'Commerce & payments', 300, 1500, 0.99, 10000,
    'client:agents, lb:edge, app:disputes, queue:case-queue, worker:case-worker, ledger:ledger, sql:case-db, audit:audit-log, partner:network',
    'agents>edge>disputes>case-db; disputes>case-queue>case-worker>ledger>case-db; case-worker>network; disputes>audit-log',
    'Low volume, long deadlines, and an audit trail that is a legal requirement rather than a nice-to-have.'],

  /* ── Social & media ────────────────────────────────────────────────────── */
  ['social-feed', 'Social feed', 'Social & media', 12000, 500, 0.99, 200000,
    'client:users, cdn:cdn, lb:edge, gateway:api-gw, app:feed-api*2, micro:timeline, cache:timeline-cache, nosql:posts, graph:social-graph, kafka:fanout-events, worker:fanout*2, blob:media',
    'users>cdn>edge>api-gw>feed-api>timeline>timeline-cache>posts; timeline>social-graph; feed-api>fanout-events>fanout>timeline-cache; cdn>media',
    'Fan-out on write against fan-out on read, which is the oldest argument in social infrastructure. This models the write side.'],
  ['chat-messaging', 'Chat and messaging', 'Social & media', 15000, 1000, 0.995, 50000,
    'client:clients, lb:edge*2, ws:gateway*3, micro:message-svc*21, cache:presence-cache, nosql:messages*2, kafka:message-bus, worker:delivery*31, push:push*2',
    'clients>edge>gateway>message-svc>messages; message-svc>message-bus>delivery>push; gateway>presence-cache',
    'Long-lived connections change the capacity question from requests per second to connections held, which the DES models and the analytic engine approximates.'],
  ['video-streaming', 'Video streaming', 'Social & media', 12000, 5000, 0.995, 150000,
    'client:viewers, dns:dns, cdn:cdn, lb:edge, app:manifest-api*24, transcode:transcoder*39, queue:encode-jobs, blob:segments, nosql:catalog, analytics:qoe*8',
    'viewers>dns>cdn>segments; viewers>edge>manifest-api>catalog; manifest-api>encode-jobs>transcoder>segments; manifest-api>qoe',
    'The CDN carries the bytes and the origin carries the metadata. Transcoding is the expensive, bursty, entirely off-path half.'],
  ['photo-sharing', 'Photo sharing', 'Social & media', 12000, 1000, 0.99, 150000,
    'client:users, cdn:cdn, lb:edge, app:api*10, queue:process-jobs, worker:resizer*7, blob:originals, blob:derivatives, nosql:metadata, search:photo-search',
    'users>cdn>derivatives; users>edge>api>metadata; api>process-jobs>resizer>originals; resizer>derivatives; api>photo-search',
    'One upload becomes six derivatives. The write path is cheap and the processing path is not.'],
  ['live-comments', 'Live comments', 'Social & media', 35000, 1500, 0.995, 100000,
    'client:viewers, lb:edge*2, ws:socket*3, micro:comment-svc*36, cache:recent, kafka:comment-bus, worker:moderator*54, nosql:comments*4',
    'viewers>edge>socket>comment-svc>recent>comments; comment-svc>comment-bus>moderator>comments',
    'Traffic follows an event, not a clock. The diurnal workload is wrong here; a spike scenario is the honest one.'],
  ['notifications-fanout', 'Notification fan-out', 'Social & media', 5000, 2500, 0.995, 20000,
    'client:services, lb:edge, app:notify-api*8, kafka:notify-bus, worker:router*16, worker:sender*6, nosql:preferences, push:push, cache:dedupe',
    'services>edge>notify-api>notify-bus>router>preferences; router>dedupe; router>sender>push',
    'One event becomes a million sends. Deduplication is the difference between a notification and a complaint.'],
  ['content-moderation', 'Content moderation', 'Social & media', 400, 4000, 0.995, 250000,
    'client:uploads, lb:edge, app:intake*13, queue:review-queue, ml:classifier*13, llm:policy-llm*52, worker:reviewer*7, nosql:decisions, audit:audit-log, blob:evidence',
    'uploads>edge>intake>review-queue>classifier>decisions; classifier>policy-llm; review-queue>reviewer>decisions; reviewer>evidence; intake>audit-log',
    'A model triages and people decide the hard cases. The queue between them is where a backlog becomes a safety problem.'],
  ['podcast-platform', 'Podcast platform', 'Social & media', 6000, 15000, 0.995, 60000,
    'client:listeners, cdn:cdn, lb:edge, app:api*5, transcode:encoder*6, queue:encode-jobs, blob:audio, nosql:episodes, search:show-search, analytics:plays*2',
    'listeners>cdn>audio; listeners>edge>api>episodes; api>show-search; api>encode-jobs>encoder>audio; api>plays',
    'Streaming without the bandwidth of video, which makes the metadata tier — not the CDN — the thing that falls over.'],
  ['news-aggregator', 'News aggregator', 'Social & media', 9000, 300, 0.995, 150000,
    'client:readers, cdn:cdn, lb:edge, app:api*2, cache:feed-cache, search:article-index, worker:crawler, queue:crawl-queue, nosql:articles, embed:embedder, vector:related',
    'readers>cdn>edge>api>feed-cache>articles; api>article-index; crawl-queue>crawler>articles; crawler>embedder>related',
    'A read-heavy front and a continuous crawl behind it. The two share a datastore and compete for it.'],
  ['community-forum', 'Community forum', 'Social & media', 4000, 400, 0.99, 80000,
    'client:members, cdn:cdn, lb:edge, web:forum, cache:thread-cache, sql:forum-db, search:post-search, queue:mod-queue, worker:mod-bot',
    'members>cdn>edge>forum>thread-cache>forum-db; forum>post-search; forum>mod-queue>mod-bot>forum-db',
    'Modest traffic with a very long tail of old threads, which is a cache-eviction problem disguised as a database problem.'],

  /* ── Data & analytics ──────────────────────────────────────────────────── */
  ['clickstream-pipeline', 'Clickstream pipeline', 'Data & analytics', 20000, 2000, 0.995, 40000,
    'client:browsers, lb:collector-lb*2, app:collector*64, kafka:event-bus, stream:enricher*4, lake:raw-lake*2, warehouse:warehouse*26, etl:loader*39, bi:dashboards*64',
    'browsers>collector-lb>collector>event-bus>enricher>raw-lake; enricher>loader>warehouse>dashboards',
    'The collector must never drop and never block. Everything downstream is allowed to be late; the collector is not allowed to be down.'],
  ['batch-etl-warehouse', 'Nightly ETL to a warehouse', 'Data & analytics', 400, 150, 0.9999, 1500,
    'client:sources, scheduler:cron, queue:job-queue, etl:extract, batch:transform, warehouse:warehouse, lake:staging, bi:reports, monitor:job-monitor',
    'sources>staging; cron>job-queue>extract>staging; extract>transform>warehouse>reports; transform>job-monitor',
    'A batch window is a latency SLO with a deadline attached. Model it at the volume of the worst night, not the average one.'],
  ['cdc-replication', 'Change data capture', 'Data & analytics', 20000, 2000, 0.995, 30000,
    'client:apps, sql:oltp*13, cdc:capture*4, kafka:change-bus, stream:transform, warehouse:analytics-db*6, nosql:read-model, monitor:lag-monitor',
    'apps>oltp>capture>change-bus>transform>analytics-db; transform>read-model; capture>lag-monitor',
    'Replication lag is the only metric that matters and it is invisible until it is a crisis. This template puts it on the canvas.'],
  ['realtime-dashboards', 'Real-time dashboards', 'Data & analytics', 3000, 2000, 0.995, 3000,
    'client:analysts, lb:edge, app:query-api*5, cache:result-cache, tsdb:metrics, warehouse:warehouse*2, kafka:live-events, stream:aggregator',
    'analysts>edge>query-api>result-cache>metrics; query-api>warehouse; live-events>aggregator>metrics',
    'Two stores with different freshness guarantees behind one query API. Which one answers is a product decision, not an infrastructure one.'],
  ['data-lakehouse', 'Lakehouse', 'Data & analytics', 1500, 4000, 0.995, 2000,
    'client:consumers, lb:edge, app:catalog-api*3, lake:lake, warehouse:compute, etl:ingest, kafka:ingest-bus, batch:compaction, bi:bi*3',
    'consumers>edge>catalog-api>lake; ingest-bus>ingest>lake; lake>compute>bi; lake>compaction',
    'Storage and compute are separate, so a slow query is a compute problem and an expensive month is a storage one. The cost model separates them.'],
  ['session-analytics', 'Session analytics', 'Data & analytics', 30000, 4000, 0.995, 80000,
    'client:apps, lb:edge, app:ingest*47, kafka:session-bus, stream:sessioniser*3, nosql:session-store*3, warehouse:warehouse*16, bi:reports*47',
    'apps>edge>ingest>session-bus>sessioniser>session-store; sessioniser>warehouse>reports',
    'Sessionisation is stateful streaming, which means a restart is not free. The DES is where that shows up.'],
  ['ab-testing', 'Experimentation platform', 'Data & analytics', 20000, 4000, 0.995, 25000,
    'client:apps, lb:edge, featureflag:assignment, cache:variant-cache, nosql:experiments, kafka:exposure-bus, stream:metrics, warehouse:results*11, bi:readouts*31',
    'apps>edge>assignment>variant-cache>experiments; assignment>exposure-bus>metrics>results>readouts',
    'Assignment is on every request, so it has an availability target higher than the product it experiments on.'],
  ['metrics-tsdb', 'Metrics platform', 'Data & analytics', 60000, 150, 0.99999, 100000,
    'client:agents, lb:ingest-lb*2, grpc:ingest*64, tsdb:tsdb*4, cache:query-cache, app:query-api, alert:alerting*37, bi:grafana',
    'agents>ingest-lb>ingest>tsdb; query-api>query-cache>tsdb; query-api>grafana; tsdb>alerting',
    'Cardinality is the capacity unit that the request rate hides. Worth opening next to the observability template.'],
  ['log-pipeline', 'Log pipeline', 'Data & analytics', 30000, 500, 0.995, 30000,
    'client:agents, lb:collector-lb*3, app:collector*64, kafka:log-bus, stream:parser*5, search:log-index*13, blob:cold-storage*4, alert:alerting*20',
    'agents>collector-lb>collector>log-bus>parser>log-index; parser>cold-storage; log-index>alerting',
    'The highest-volume, lowest-value-per-record system most companies run. Its whole design is a tiering argument.'],
  ['reverse-etl', 'Reverse ETL', 'Data & analytics', 600, 3000, 0.99, 30000,
    'client:schedule, scheduler:cron*2, warehouse:warehouse, etl:sync, queue:sync-queue, worker:pusher, crm:crm, partner:saas-tools',
    'schedule>cron>sync-queue>sync>warehouse; sync>pusher>crm; pusher>saas-tools',
    'Pushing warehouse data back into operational tools, where rate limits on someone else\'s API set the pace.'],

  /* ── AI & ML ───────────────────────────────────────────────────────────── */
  ['rag-chatbot', 'RAG chatbot', 'AI & ML', 60, 4000, 0.995, 100000,
    'client:users, lb:edge, gateway:api-gw, app:chat-api, embed:embedder, vector:vector-db, llm:llm*11, cache:answer-cache, nosql:chat-history, guard:safety',
    'users>edge>api-gw>chat-api>answer-cache>chat-history; chat-api>embedder>vector-db; chat-api>llm>safety',
    'Retrieval is fast and generation is not, so almost the entire latency budget is one component. The quick-fix engine has very little to work with, which is itself the lesson.'],
  ['llm-gateway', 'LLM gateway', 'AI & ML', 120, 4000, 0.995, 200000,
    'client:apps, lb:edge, ratelimiter:quota, gateway:llm-gw, cache:prompt-cache, llm:primary*4, llm:fallback*16, llmobs:observability, nosql:usage-log',
    'apps>edge>quota>llm-gw>prompt-cache>primary; llm-gw>fallback; llm-gw>usage-log; llm-gw>observability',
    'A router in front of expensive, slow, rate-limited capacity. The fallback path is the availability story and the cache is the cost story.'],
  ['embedding-indexer', 'Embedding indexer', 'AI & ML', 120, 400, 0.995, 4000,
    'client:sources, queue:doc-queue, worker:chunker*7, embed:embedder*3, vector:vector-db, blob:documents, nosql:doc-meta, monitor:index-monitor',
    'sources>doc-queue>chunker>documents; chunker>embedder>vector-db; chunker>doc-meta; embedder>index-monitor',
    'An entirely asynchronous pipeline whose only user-visible property is how stale the index is.'],
  ['recommendation-engine', 'Recommendations', 'AI & ML', 4000, 2000, 0.995, 25000,
    'client:apps, lb:edge, app:reco-api*24, cache:reco-cache, featurestore:features, ml:ranker*31, vector:candidates, kafka:interaction-bus, batch:trainer*6, warehouse:training-data*6',
    'apps>edge>reco-api>reco-cache>candidates; reco-api>features>ranker; reco-api>interaction-bus>training-data; training-data>trainer',
    'Serving and training share a feature store, which is where the two halves of an ML system usually disagree about what a feature means.'],
  ['fraud-scoring', 'Fraud scoring', 'AI & ML', 1200, 500, 0.995, 5000,
    'client:payments, lb:edge, app:score-api*7, cache:feature-cache, featurestore:features, ml:model*5, nosql:rules, kafka:decision-bus, audit:audit-log',
    'payments>edge>score-api>feature-cache>features; score-api>model; score-api>rules; score-api>decision-bus; score-api>audit-log',
    'Inline on a payment with a 150ms budget: too slow and the transaction is declined by timeout, which costs more than the fraud did.'],
  ['image-generation', 'Image generation', 'AI & ML', 15, 8000, 0.995, 8000,
    'client:users, lb:edge, app:api, queue:gen-queue, imagen:generator*2, blob:outputs, cache:result-cache, guard:safety, nosql:jobs',
    'users>edge>api>jobs; api>gen-queue>generator>outputs; generator>safety; api>result-cache',
    'Seconds per request, not milliseconds. The queue is the product: it is what turns a 12-second wait into a job someone can walk away from.'],
  ['speech-transcription', 'Speech to text', 'AI & ML', 20, 4000, 0.995, 25000,
    'client:uploads, lb:edge, app:api, blob:audio, queue:asr-queue, ml:asr*2, llm:summariser*6, nosql:transcripts, search:transcript-index',
    'uploads>edge>api>audio; api>asr-queue>asr>transcripts; asr>summariser>transcripts; transcripts>transcript-index',
    'Long jobs with a wide worker pool. Little\'s law does more work here than any queueing formula.'],
  ['agentic-workflow', 'Agent workflow', 'AI & ML', 10, 8000, 0.99, 15000,
    'client:users, lb:edge, aiagent:orchestrator, agentgraph:planner, llm:reasoner*2, sandbox:tools, vector:memory, nosql:runs, llmobs:traces, guard:safety',
    'users>edge>orchestrator>planner>reasoner; orchestrator>tools; orchestrator>memory; orchestrator>runs; reasoner>safety; orchestrator>traces',
    'Multi-step, so latency compounds and any single step failing fails the run. The retry-storm scenario is unusually instructive here.'],
  ['model-finetuning', 'Fine-tuning pipeline', 'AI & ML', 5, 200000, 0.995, 25000,
    'client:jobs, scheduler:cron, queue:train-queue, finetune:trainer*8, lake:datasets, blob:checkpoints, warehouse:eval-results, monitor:train-monitor',
    'jobs>train-queue>trainer>datasets; trainer>checkpoints; trainer>eval-results; cron>train-queue; trainer>train-monitor',
    'Hours per job and no user waiting. Included because the cost model, not the latency model, is what this design is judged on.'],
  ['semantic-search', 'Semantic search', 'AI & ML', 600, 400, 0.995, 20000,
    'client:users, lb:edge, app:search-api*5, cache:query-cache, embed:embedder*4, vector:vector-db, search:keyword-index, ml:reranker*7',
    'users>edge>search-api>query-cache>keyword-index; search-api>embedder>vector-db; search-api>reranker',
    'Hybrid retrieval: keyword and vector in parallel, then a reranker. Three components in series inside a 400ms budget.'],

  /* ── Streaming & events ────────────────────────────────────────────────── */
  ['event-sourced-orders', 'Event-sourced orders', 'Streaming & events', 4000, 400, 0.995, 15000,
    'client:apps, lb:edge, app:command-api*4, kafka:event-log, stream:projector, nosql:read-model, sql:snapshot-store, app:query-api*4',
    'apps>edge>command-api>event-log>projector>read-model; projector>snapshot-store; apps>edge>query-api>read-model',
    'Writes and reads are separate systems that happen to share a name. Projection lag is the property to gate on.'],
  ['saga-orchestration', 'Saga orchestration', 'Streaming & events', 1500, 250, 0.995, 50000,
    'client:orders, lb:edge, saga:orchestrator*2, micro:payment, micro:inventory, micro:shipping, kafka:saga-bus, sql:saga-state, queue:compensation',
    'orders>edge>orchestrator>saga-bus>payment; saga-bus>inventory; saga-bus>shipping; orchestrator>saga-state; orchestrator>compensation',
    'A distributed transaction that admits it is not one. The compensation path exists precisely because a step will fail.'],
  ['outbox-pattern', 'Transactional outbox', 'Streaming & events', 6000, 1500, 0.995, 30000,
    'client:apps, lb:edge, app:service*10, sql:db*4, cdc:outbox-reader, kafka:event-bus, worker:consumer*19, nosql:downstream',
    'apps>edge>service>db>outbox-reader>event-bus>consumer>downstream',
    'The smallest correct answer to "write to the database and publish an event". Worth having as a reference next to the wrong ones.'],
  ['kafka-fanout', 'Event fan-out', 'Streaming & events', 40000, 3000, 0.995, 80000,
    'client:producers, lb:edge*2, app:producer-api*62, kafka:topic, worker:consumer-a*42, worker:consumer-b*42, worker:consumer-c*42, nosql:store-a*3, warehouse:store-b*14, search:store-c*6',
    'producers>edge>producer-api>topic>consumer-a>store-a; topic>consumer-b>store-b; topic>consumer-c>store-c',
    'One topic, three consumer groups with different speeds. The slowest sets the retention you need.'],
  ['stream-join', 'Stream enrichment and join', 'Streaming & events', 25000, 2000, 0.995, 20000,
    'client:sources, kafka:input-a, kafka:input-b, stream:joiner*2, cache:lookup-cache, nosql:reference-data, kafka:output, warehouse:sink*13',
    'sources>input-a>joiner>output>sink; sources>input-b>joiner; joiner>lookup-cache>reference-data',
    'A stateful join with a lookup on the side. State size, not throughput, is what makes this one fall over.'],
  ['dead-letter', 'Dead-letter handling', 'Streaming & events', 8000, 1000, 0.995, 6000,
    'client:producers, kafka:main-topic, worker:consumer*25, queue:retry-queue, queue:dlq, worker:dlq-handler, nosql:store, alert:alerting',
    'producers>main-topic>consumer>store; consumer>retry-queue>consumer; consumer>dlq>dlq-handler>store; dlq>alerting',
    'The path a message takes when it cannot be processed. Most designs draw the happy path only, which is why this is its own template.'],
  ['webhook-delivery', 'Webhook delivery', 'Streaming & events', 1500, 1500, 0.995, 100000,
    'client:events, lb:edge, app:webhook-api*8, queue:delivery-queue, worker:deliverer*16, cache:endpoint-cache, nosql:subscriptions, partner:customer-endpoints*3, queue:retry',
    'events>edge>webhook-api>delivery-queue>deliverer>customer-endpoints; deliverer>endpoint-cache>subscriptions; deliverer>retry',
    'Every delivery depends on someone else\'s uptime. Retry budgets are the difference between resilience and a self-inflicted denial of service.'],
  ['scheduled-jobs', 'Scheduled jobs', 'Streaming & events', 200, 400, 0.995, 800,
    'client:schedule, scheduler:cron, zk:leader-election, queue:job-queue, worker:runner, sql:job-state, monitor:job-monitor, alert:alerting',
    'schedule>cron>job-queue>runner>job-state; cron>leader-election; runner>job-monitor>alerting',
    'The leader election is what stops a job from running twice. Take it out and the failure is silent and expensive.'],
  ['priority-queues', 'Priority queues', 'Streaming & events', 12000, 1500, 0.995, 25000,
    'client:producers, lb:edge, app:intake*19, queue:high-priority, queue:normal-priority, queue:bulk, worker:fast-workers*25, worker:bulk-workers*13, sql:results*8',
    'producers>edge>intake>high-priority>fast-workers>results; intake>normal-priority>fast-workers; intake>bulk>bulk-workers>results',
    'Three classes of work sharing worker pools. Starvation of the bulk queue is a design choice; starvation of the priority queue is a bug.'],
  ['backpressure', 'Backpressure and shedding', 'Streaming & events', 30000, 1500, 0.995, 60000,
    'client:producers, lb:edge, ratelimiter:shedder*2, app:intake*47, queue:bounded-queue*2, worker:processor*47, cache:state, nosql:store, monitor:depth-monitor',
    'producers>edge>shedder>intake>bounded-queue>processor>state>store; bounded-queue>depth-monitor',
    'A bounded queue that sheds rather than a growing one that lies. Best read in the DES tab, where the bound actually binds.'],

  /* ── Platform & infrastructure ─────────────────────────────────────────── */
  ['k8s-microservices', 'Kubernetes microservices', 'Platform & infrastructure', 10000, 300, 0.995, 4000,
    'client:users, lb:edge, k8sgw:ingress, mesh:sidecar, micro:svc-a*4, micro:svc-b*4, micro:svc-c*4, cache:shared-cache, sql:db-a*2, nosql:db-b, registry:discovery, config:config',
    'users>edge>ingress>sidecar>svc-a>db-a; sidecar>svc-b>shared-cache>db-b; sidecar>svc-c; svc-a>discovery; svc-b>config',
    'The default shape of a mid-size estate. The mesh sidecar adds a hop to every call, which is a latency line item people forget to count.'],
  ['service-mesh', 'Service mesh', 'Platform & infrastructure', 15000, 800, 0.995, 80000,
    'client:users, lb:edge, gateway:ingress-gw, mesh:mesh*2, micro:frontend*6, micro:backend*6, micro:data-svc*6, sql:db*4, tracing:tracing, iam:mtls',
    'users>edge>ingress-gw>mesh>frontend>backend>data-svc>db; mesh>mtls; mesh>tracing',
    'Every hop goes through the mesh, so the mesh\'s own availability multiplies into every service behind it.'],
  ['multi-region', 'Multi-region active-active', 'Platform & infrastructure', 20000, 600, 0.995, 50000,
    'client:users, gslb:gslb, lb:lb-east, lb:lb-west, app:app-east*16, app:app-west*16, sql:db-east*2, sql:db-west*3, cache:cache-east, cache:cache-west, kafka:replication',
    'users>gslb>lb-east>app-east>cache-east>db-east; gslb>lb-west>app-west>cache-west>db-west; db-east>replication>db-west',
    'Two of everything and a replication link between them. Losing a region should cost latency, not availability — this is where you check that.'],
  ['blue-green', 'Blue-green deployment', 'Platform & infrastructure', 8000, 500, 0.995, 2500,
    'client:users, lb:router, app:blue*7, app:green*7, sql:shared-db, cache:shared-cache, cicd:pipeline, monitor:health',
    'users>router>blue>shared-cache>shared-db; router>green>shared-cache; pipeline>green; blue>health',
    'Two full stacks and one database, which is where blue-green quietly becomes a schema-compatibility problem.'],
  ['canary-rollout', 'Canary rollout', 'Platform & infrastructure', 12000, 500, 0.995, 40000,
    'client:users, lb:edge, gateway:traffic-split, app:stable*10, app:canary*10, cache:cache, sql:db*2, monitor:metrics, alert:auto-rollback*2',
    'users>edge>traffic-split>stable>cache>db; traffic-split>canary>cache; stable>metrics>auto-rollback',
    'One replica takes a slice of traffic. The question the model answers is how big a slice you need before a regression is detectable.'],
  ['api-gateway-platform', 'API gateway platform', 'Platform & infrastructure', 25000, 300, 0.995, 200000,
    'client:consumers, dns:dns, waf:waf, lb:edge, gateway:api-gw*2, ratelimiter:limiter, iam:authz*2, cache:policy-cache, micro:upstream-a*9, micro:upstream-b*9, nosql:config-store',
    'consumers>dns>waf>edge>api-gw>limiter>upstream-a; api-gw>authz>policy-cache>config-store; api-gw>upstream-b',
    'Five components before a request reaches anything that does work. Each is small; the sum is a third of the latency budget.'],
  ['ci-cd-pipeline', 'CI/CD pipeline', 'Platform & infrastructure', 100, 4000, 0.99, 1000,
    'client:commits, cicd:pipeline, queue:build-queue, sandbox:build-agents*2, containerreg:registry, apitest:tests, qgate:quality-gate, blob:artifacts, k8s:deploy-target',
    'commits>pipeline>build-queue>build-agents>artifacts; build-agents>registry; build-agents>tests>quality-gate; quality-gate>deploy-target',
    'The system that ships every other system. Its latency SLO is measured in minutes and it is still the one developers complain about most.'],
  ['feature-flags', 'Feature flag platform', 'Platform & infrastructure', 20000, 50, 0.995, 200000,
    'client:apps, cdn:flag-cdn, lb:edge, featureflag:evaluator*2, cache:flag-cache, nosql:flag-store, kafka:audit-stream, app:admin-api',
    'apps>flag-cdn>evaluator>flag-cache>flag-store; apps>edge>evaluator; admin-api>flag-store; evaluator>audit-stream',
    'Evaluated on every request in every service, so it needs an availability figure most teams have never had to hit.'],
  ['config-discovery', 'Config and service discovery', 'Platform & infrastructure', 30000, 100, 0.995, 50000,
    'client:services, lb:edge, registry:discovery*2, config:config-server*3, zk:consensus*3, cache:local-cache, nosql:store*2',
    'services>edge>discovery>local-cache>store; services>edge>config-server>consensus; config-server>store',
    'The control plane everything else assumes is up. Model it down and half the estate becomes unreachable in a way no dashboard predicts.'],
  ['observability-stack', 'Observability stack', 'Platform & infrastructure', 30000, 800, 0.995, 100000,
    'client:agents, lb:collector-lb*3, otel:collector*2, tsdb:metrics*2, search:logs*9, tracing:traces, apm:apm, alert:alerting*8, bi:dashboards*36, blob:cold-storage*3',
    'agents>collector-lb>collector>metrics>dashboards; collector>logs>cold-storage; collector>traces>apm; metrics>alerting',
    'The system you rely on to tell you the other systems are broken, and the one most likely to be broken at the same time.'],

  /* ── Finance & regulated ───────────────────────────────────────────────── */
  ['core-banking', 'Core banking ledger', 'Finance & regulated', 3000, 2000, 0.995, 15000,
    'client:channels, lb:edge, gateway:api-gw, app:core*5, ledger:ledger*3, sql:accounts, cache:balance-cache, kafka:posting-stream, audit:audit-log, backup:backup',
    'channels>edge>api-gw>core>ledger>accounts; core>balance-cache>accounts; ledger>posting-stream; core>audit-log; accounts>backup',
    'Five nines and double-entry. The cache in front of balances is the single most dangerous component on the canvas.'],
  ['card-authorization', 'Card authorisation', 'Finance & regulated', 3000, 1500, 0.995, 100000,
    'client:terminals, lb:edge, app:auth-svc*13, cache:card-cache, ml:fraud-model*10, hsm:hsm, ledger:ledger*4, sql:txn-db, partner:scheme*3',
    'terminals>edge>auth-svc>card-cache>txn-db; auth-svc>fraud-model; auth-svc>hsm; auth-svc>ledger; auth-svc>scheme',
    'A hundred milliseconds end to end, including a fraud model and a hardware security module. Every hop is measured in single-digit milliseconds.'],
  ['kyc-onboarding', 'KYC onboarding', 'Finance & regulated', 200, 1500, 0.99, 5000,
    'client:applicants, lb:edge, app:onboarding, queue:verify-queue, worker:verifier, ml:doc-check, partner:bureau, blob:documents, sql:cases, audit:audit-log, pii:redaction',
    'applicants>edge>onboarding>cases; onboarding>verify-queue>verifier>bureau; verifier>doc-check>documents; verifier>redaction; onboarding>audit-log',
    'Slow by design and legally obliged to keep records. The redaction service is on the path because the alternative is a breach.'],
  ['trading-orderbook', 'Trading order book', 'Finance & regulated', 20000, 200, 0.995, 100000,
    'client:traders, lb:gateway-lb*2, gateway:order-gw*4, app:matching-engine*39, cache:book-cache, kafka:market-data, ledger:positions*6, tsdb:tick-store, audit:audit-log*2',
    'traders>gateway-lb>order-gw>matching-engine>book-cache>positions; matching-engine>market-data>tick-store; order-gw>audit-log',
    'Twenty milliseconds is the whole budget. Almost nothing in the catalog is fast enough to be added to this design casually.'],
  ['clearing-settlement', 'Clearing and settlement', 'Finance & regulated', 500, 4000, 0.99, 30000,
    'client:trades, queue:trade-queue, worker:matcher*2, batch:netting, ledger:ledger, sql:settlement-db, partner:custodian, audit:audit-log, backup:archive',
    'trades>trade-queue>matcher>ledger>settlement-db; matcher>netting>settlement-db; settlement-db>custodian; matcher>audit-log; settlement-db>archive',
    'Batch windows with hard external deadlines. Missing one is a regulatory event, not a latency regression.'],
  ['insurance-claims', 'Insurance claims', 'Finance & regulated', 400, 2000, 0.99, 15000,
    'client:claimants, lb:edge, app:claims, queue:assessment-queue, worker:assessor, ml:damage-model, blob:evidence, sql:claims-db, partner:repairer, audit:audit-log',
    'claimants>edge>claims>claims-db; claims>assessment-queue>assessor>damage-model>evidence; assessor>repairer; claims>audit-log',
    'A long-running human workflow with a model in the middle of it. The queue depth is measured in days.'],
  ['loan-origination', 'Loan origination', 'Finance & regulated', 300, 1500, 0.99, 15000,
    'client:applicants, lb:edge, app:origination, ml:credit-model, partner:credit-bureau, queue:underwrite-queue, worker:underwriter, ledger:ledger, sql:loan-db, audit:audit-log',
    'applicants>edge>origination>credit-model; origination>credit-bureau; origination>underwrite-queue>underwriter>ledger>loan-db; origination>audit-log',
    'An external bureau on the critical path with a latency you do not control and a contract that says you must retry politely.'],
  ['audit-trail', 'Immutable audit trail', 'Finance & regulated', 20000, 4000, 0.995, 25000,
    'client:services, lb:edge, app:audit-api*31, digest:hash-chain, kafka:audit-stream, worker:writer*62, blob:immutable-store*2, search:audit-index*4, backup:archive*6',
    'services>edge>audit-api>hash-chain>audit-stream>writer>immutable-store; writer>audit-index; immutable-store>archive',
    'Append-only with a hash chain, so a gap is detectable. Availability matters more than latency: a lost audit record cannot be re-created.'],
  ['regulatory-reporting', 'Regulatory reporting', 'Finance & regulated', 100, 3000, 0.99, 6000,
    'client:schedule, scheduler:cron, warehouse:warehouse, batch:report-builder, etl:extractor, sql:source-db, blob:submissions, partner:regulator, audit:audit-log',
    'schedule>cron>extractor>source-db; extractor>warehouse>report-builder>submissions; submissions>regulator; report-builder>audit-log',
    'Deadlines set by law rather than by product. The batch window is the SLO and there is no negotiating it.'],
  ['treasury-recon', 'Treasury reconciliation', 'Finance & regulated', 200, 2000, 0.995, 2000,
    'client:feeds, mft:file-transfer, queue:recon-queue, batch:matcher, ledger:ledger, sql:recon-db, alert:breaks, bi:reports, audit:audit-log',
    'feeds>file-transfer>recon-queue>matcher>ledger>recon-db; matcher>breaks; recon-db>reports; matcher>audit-log',
    'Files arrive from banks on their schedule, not yours. Everything downstream is a batch process with a queue in front of it.'],

  /* ── IoT, mobility & realtime ──────────────────────────────────────────── */
  ['iot-telemetry', 'IoT telemetry ingest', 'IoT, mobility & realtime', 40000, 150, 0.995, 200000,
    'client:devices, gslb:gslb, lb:ingest-lb*4, mq:mqtt-broker*11, stream:decoder*4, tsdb:tsdb*2, kafka:event-bus, nosql:device-registry*8, alert:alerting*16',
    'devices>gslb>ingest-lb>mqtt-broker>decoder>tsdb; decoder>event-bus; mqtt-broker>device-registry; tsdb>alerting',
    'A hundred thousand small messages per second from devices that will not retry politely. The broker is the entire capacity question.'],
  ['fleet-tracking', 'Fleet tracking', 'IoT, mobility & realtime', 30000, 600, 0.995, 20000,
    'client:vehicles, lb:ingest-lb, app:ingest*47, geoidx:geo-index, kafka:position-bus, stream:matcher*2, tsdb:history, cache:live-positions, app:query-api',
    'vehicles>ingest-lb>ingest>position-bus>matcher>geo-index; matcher>history; ingest>live-positions; query-api>live-positions',
    'Write-heavy with a small hot read set — the current position of everything, which almost fits in memory and therefore should.'],
  ['ride-hailing', 'Ride-hailing dispatch', 'IoT, mobility & realtime', 20000, 1500, 0.995, 150000,
    'client:riders, client:drivers, lb:edge, gateway:api-gw*2, app:dispatch*31, geoidx:geo-index, cache:driver-cache, ml:eta-model*25, kafka:trip-events, nosql:trips, push:notify',
    'riders>edge>api-gw>dispatch>geo-index; drivers>edge>api-gw>dispatch>driver-cache; dispatch>eta-model; dispatch>trip-events>trips; dispatch>notify',
    'Matching supply and demand in real time, where a slow match is a lost ride and a wrong match is two of them.'],
  ['delivery-eta', 'Delivery ETA', 'IoT, mobility & realtime', 12000, 2000, 0.995, 30000,
    'client:apps, lb:edge, app:eta-api*19, cache:eta-cache, ml:eta-model*37, featurestore:features, geoidx:routing, kafka:position-stream, tsdb:history',
    'apps>edge>eta-api>eta-cache>routing; eta-api>eta-model>features; position-stream>history; eta-model>history',
    'A model call on the read path with a cache in front of it. How stale an ETA may be is the product decision the architecture encodes.'],
  ['smart-metering', 'Smart metering', 'IoT, mobility & realtime', 40000, 5000, 0.995, 60000,
    'client:meters, mq:collector*5, kafka:reading-bus, stream:validator*4, tsdb:readings*2, batch:billing-run*21, warehouse:warehouse*21, billing:rating*16, sql:accounts*13',
    'meters>collector>reading-bus>validator>readings; readings>billing-run>rating>accounts; validator>warehouse',
    'Readings arrive continuously and are billed monthly, so the same data is streamed and batched. Both paths must agree.'],
  ['connected-car', 'Connected vehicle platform', 'IoT, mobility & realtime', 25000, 600, 0.995, 60000,
    'client:vehicles, gslb:gslb, mq:vehicle-broker*2, stream:processor, kafka:telemetry-bus, blob:firmware*2, app:ota-api*20, nosql:vehicle-state, tsdb:diagnostics, iam:device-identity',
    'vehicles>gslb>vehicle-broker>processor>telemetry-bus>diagnostics; processor>vehicle-state; vehicles>ota-api>firmware; vehicle-broker>device-identity',
    'Two-way: telemetry up and firmware down. The over-the-air path is the one with real consequences for getting it wrong.'],
  ['geofencing', 'Geofencing', 'IoT, mobility & realtime', 15000, 1000, 0.995, 60000,
    'client:devices, lb:edge*2, app:location-api*54, geoidx:fence-index, cache:fence-cache, kafka:event-bus, worker:notifier*54, nosql:fences, push:push*3',
    'devices>edge>location-api>fence-cache>fence-index; fence-cache>fences; location-api>event-bus>notifier>push',
    'Every position update is a spatial query. The index is the capacity ceiling and the cache is the only thing keeping it reachable.'],
  ['realtime-multiplayer', 'Real-time multiplayer', 'IoT, mobility & realtime', 60000, 500, 0.995, 80000,
    'client:players, gslb:gslb, ws:session-server*3, cache:game-state, nosql:persistence, kafka:match-events, app:matchmaker*47, zk:coordination*5',
    'players>gslb>session-server>game-state>persistence; session-server>match-events; players>matchmaker>coordination; matchmaker>session-server',
    'Sixty-millisecond budget with state held in memory per session. Nothing about this design survives a stateless-service assumption.'],
  ['collaborative-editing', 'Collaborative editing', 'IoT, mobility & realtime', 20000, 800, 0.995, 50000,
    'client:editors, lb:edge, ws:sync-server*2, cache:doc-state, kafka:op-log, worker:persister*7, blob:documents, nosql:doc-meta*2, app:api',
    'editors>edge>sync-server>doc-state>op-log>persister>documents; sync-server>doc-meta; api>doc-meta',
    'Operations must be ordered and never lost, which makes the op log the source of truth and the document store a projection of it.'],
  ['presence-service', 'Presence', 'IoT, mobility & realtime', 30000, 500, 0.995, 80000,
    'client:clients, lb:edge*3, ws:presence-gw*5, cache:presence-cache*2, kafka:presence-bus, worker:fanout*64, nosql:subscriptions*5',
    'clients>edge>presence-gw>presence-cache; presence-gw>presence-bus>fanout>subscriptions',
    'Enormous rate, tiny payload, no durability requirement. The one system where losing data is genuinely fine.'],

  /* ── Enterprise & integration ──────────────────────────────────────────── */
  ['erp-integration', 'ERP integration', 'Enterprise & integration', 800, 2500, 0.995, 15000,
    'client:apps, lb:edge, gateway:api-gw, esb:integration-bus, erp:erp*2, queue:sync-queue, worker:sync*2, sql:staging, monitor:sync-monitor',
    'apps>edge>api-gw>integration-bus>erp; integration-bus>sync-queue>sync>staging; sync>erp; sync>sync-monitor',
    'The ERP is slow, licensed per call, and cannot be scaled. Everything in front of it exists to protect it.'],
  ['crm-sync', 'CRM synchronisation', 'Enterprise & integration', 600, 2000, 0.995, 4000,
    'client:apps, lb:edge, app:sync-api, queue:sync-queue, worker:syncer*2, crm:crm, cache:mapping-cache, sql:mapping-db, alert:conflict-alerts',
    'apps>edge>sync-api>sync-queue>syncer>crm; syncer>mapping-cache>mapping-db; syncer>conflict-alerts',
    'Bidirectional sync, which means conflicts. The mapping store is the only thing that makes them resolvable rather than merely detectable.'],
  ['mainframe-offload', 'Mainframe offload', 'Enterprise & integration', 2000, 800, 0.995, 60000,
    'client:channels, lb:edge, gateway:api-gw, app:facade*4, cache:read-cache, mainframe:mainframe*3, cdc:capture, kafka:change-bus, nosql:read-model',
    'channels>edge>api-gw>facade>read-cache>read-model; facade>mainframe; mainframe>capture>change-bus>read-model',
    'Reads move off the mainframe and writes stay on it. The cache and the read model are how a system you cannot change gets modernised anyway.'],
  ['b2b-file-exchange', 'B2B file exchange', 'Enterprise & integration', 100, 600, 0.99, 2000,
    'client:partners, mft:sftp-gateway, blob:landing-zone, queue:file-queue, worker:parser, sql:staging, esb:integration-bus, audit:audit-log, alert:alerting',
    'partners>sftp-gateway>landing-zone>file-queue>parser>staging; parser>integration-bus; parser>audit-log; parser>alerting',
    'Files, not APIs, on a schedule you do not set. Included because a great deal of real integration still looks exactly like this.'],
  ['esb-modernisation', 'ESB modernisation', 'Enterprise & integration', 1500, 300, 0.995, 10000,
    'client:consumers, lb:edge, gateway:api-gw, esb:legacy-bus, micro:new-svc-a, micro:new-svc-b, kafka:event-bus, sql:legacy-db, nosql:new-db',
    'consumers>edge>api-gw>legacy-bus>legacy-db; api-gw>new-svc-a>new-db; new-svc-a>event-bus>new-svc-b; new-svc-b>new-db',
    'Strangler-fig in progress: two architectures behind one gateway, and a gate that has to hold across both.'],
  ['partner-api-portal', 'Partner API portal', 'Enterprise & integration', 3000, 400, 0.995, 15000,
    'client:partners, waf:waf, lb:edge, gateway:api-gw, ratelimiter:quota, iam:oauth, app:portal*3, micro:backend, nosql:usage, sql:partner-db*2',
    'partners>waf>edge>api-gw>quota>backend>partner-db; api-gw>oauth; partners>edge>portal>partner-db; api-gw>usage',
    'External consumers you have a contract with, which turns the rate limiter from a safety valve into a commercial instrument.'],
  ['document-processing', 'Document processing', 'Enterprise & integration', 30, 4000, 0.995, 80000,
    'client:uploads, lb:edge, app:intake, blob:documents, queue:ocr-queue, ml:ocr*2, llm:extractor*13, search:doc-index, sql:extracted-data, pii:redaction',
    'uploads>edge>intake>documents; intake>ocr-queue>ocr>extractor>extracted-data; extractor>redaction; extracted-data>doc-index',
    'OCR then extraction then redaction, in series, each measured in seconds. A pipeline whose latency budget is dominated by two models.'],
  ['workflow-approvals', 'Approval workflows', 'Enterprise & integration', 400, 1000, 0.995, 8000,
    'client:staff, lb:edge, app:workflow, saga:orchestrator, queue:task-queue, worker:notifier, sql:workflow-db, push:email, audit:audit-log',
    'staff>edge>workflow>orchestrator>workflow-db; orchestrator>task-queue>notifier>email; workflow>audit-log',
    'Humans are the slow component and the orchestrator has to survive them being on holiday. State outlives every process here.'],
  ['hybrid-cloud', 'Hybrid cloud migration', 'Enterprise & integration', 4000, 1000, 0.995, 25000,
    'client:users, gslb:gslb, lb:cloud-lb, lb:onprem-lb, app:cloud-app*4, app:onprem-app*5, sql:onprem-db*2, nosql:cloud-db, cdc:replication, kafka:sync-bus, bastion:link*7',
    'users>gslb>cloud-lb>cloud-app>cloud-db; gslb>onprem-lb>onprem-app>onprem-db; onprem-db>replication>sync-bus>cloud-db; cloud-app>link>onprem-app',
    'Two data centres with different physics and a link between them whose latency is on the request path more often than the diagram suggests.'],
  ['disaster-recovery', 'Disaster recovery', 'Enterprise & integration', 6000, 2000, 0.995, 15000,
    'client:users, gslb:gslb, lb:primary-lb, lb:dr-lb, app:primary*5, app:standby*5, sql:primary-db, sql:dr-db*3, backup:backups, blob:snapshots, monitor:failover-monitor',
    'users>gslb>primary-lb>primary>primary-db; gslb>dr-lb>standby>dr-db; primary-db>backups>snapshots; primary-db>dr-db; primary>failover-monitor',
    'A standby sized for the day it is needed rather than the days it is not. Run the region-loss scenario and see whether two replicas were ever going to be enough.'],
]
