#!/usr/bin/env node
// The bundle, on a budget.
//
// The canvas is 500 kB of JavaScript that people download before they can look
// at anything, and nothing has ever noticed it growing. A budget fixes that,
// but a budget on its own only ever tells you the bad news — "over by 12 kB" —
// and leaves you to find the cause by bisecting your own week.
//
// So this also attributes the bytes. Rollup already wrote a source map, and a
// source map is a per-byte record of which source file each generated byte came
// from. Decoding it gives a real breakdown: how much of the bundle is React,
// how much is the component catalog, how much is the hundred templates. When
// the budget goes red, the table underneath it says what moved.
//
// Sizes are gzipped, because that is what the network actually carries.

import { readFileSync, existsSync, readdirSync } from 'node:fs'
import { gzipSync } from 'node:zlib'
import { join, dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const DIST = join(ROOT, 'apps/canvas/dist/assets')

// Gzipped kilobytes. Raised deliberately, never by reflex: a bundle that grows
// every week and a budget that grows with it are the same thing as no budget.
const BUDGET = {
  js: 180,
  css: 12,
  artifact: 190,
}

const kb = (n) => n / 1024
const gz = (buf) => kb(gzipSync(buf).length)
const fmt = (n) => `${n.toFixed(1)} kB`

/* ── decode the source map ────────────────────────────────────────────────── */

const B64 = new Map([...'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'].map((c, i) => [c, i]))

/** Base64 VLQ: 5 payload bits per character, low bit of the value is the sign. */
function* vlq(s) {
  let value = 0, shift = 0
  for (const ch of s) {
    const d = B64.get(ch)
    value |= (d & 31) << shift
    if (d & 32) { shift += 5; continue }
    const negative = value & 1
    value >>= 1
    yield negative ? (value === 0 ? -0x80000000 : -value) : value
    value = 0; shift = 0
  }
}

/**
 * Generated bytes per source file.
 *
 * Each generated line's segments are ordered by column, so the span a segment
 * accounts for runs to the next segment's column — or to the end of the line
 * for the last one. Summing those spans per source is the attribution.
 */
function attribute(code, map) {
  const lines = code.split('\n')
  const bytes = new Array(map.sources.length).fill(0)
  let srcIdx = 0
  map.mappings.split(';').forEach((lineSegs, lineNo) => {
    if (!lineSegs) return
    const lineLen = lines[lineNo]?.length ?? 0
    const cols = []
    let genCol = 0
    for (const seg of lineSegs.split(',')) {
      const f = [...vlq(seg)]
      if (!f.length) continue
      genCol += f[0]
      if (f.length >= 4) srcIdx += f[1]
      cols.push([genCol, f.length >= 4 ? srcIdx : -1])
    }
    for (let i = 0; i < cols.length; i++) {
      const [col, si] = cols[i]
      if (si < 0) continue
      const end = i + 1 < cols.length ? cols[i + 1][0] : lineLen
      bytes[si] += Math.max(0, end - col)
    }
  })
  return bytes
}

/** Which bucket a source file belongs to, as a person would name it. */
function bucket(source) {
  const s = source.replace(/\\/g, '/')
  const ws = s.match(/packages\/([^/]+)\//)
  if (ws) return `@archsim/${ws[1]}`
  const nm = s.match(/node_modules\/((?:@[^/]+\/)?[^/]+)/)
  if (nm) return nm[1]
  // Rollup writes the canvas's own files relative to the chunk, so they arrive
  // as bare `../../src/...` with nothing naming the app.
  if (/(^|\/)src\//.test(s)) return 'canvas'
  return 'other'
}

/* ── measure ──────────────────────────────────────────────────────────────── */

if (!existsSync(DIST)) {
  console.error('budget: no build to measure — run `npm run build` first.')
  process.exit(1)
}

const assets = readdirSync(DIST)
const jsName = assets.find((f) => f.endsWith('.js'))
const cssName = assets.find((f) => f.endsWith('.css'))
const js = readFileSync(join(DIST, jsName))
const css = cssName ? readFileSync(join(DIST, cssName)) : Buffer.alloc(0)

/** @type {[name: string, gzippedKb: number, budgetKb: number, note: string][]} */
const rows = [
  ['js', gz(js), BUDGET.js, `${jsName} (${fmt(kb(js.length))} raw)`],
  ['css', gz(css), BUDGET.css, cssName ? `${cssName} (${fmt(kb(css.length))} raw)` : '—'],
]

const artifact = join(ROOT, 'archsim-studio.html')
if (existsSync(artifact)) {
  const h = readFileSync(artifact)
  rows.push(['artifact', gz(h), BUDGET.artifact, `single-file page (${fmt(kb(h.length))} raw)`])
}

console.log('asset      gzipped    budget   headroom')
for (const [name, size, budget, note] of rows) {
  const over = size > budget
  const head = budget - size
  console.log(
    `${name.padEnd(10)} ${fmt(size).padStart(8)}  ${fmt(budget).padStart(8)}  ` +
    `${(head >= 0 ? '+' : '') + fmt(head)}${over ? '  OVER' : ''}`.padEnd(18) + note,
  )
}

/* ── attribution ──────────────────────────────────────────────────────────── */

const mapPath = join(DIST, `${jsName}.map`)
if (existsSync(mapPath)) {
  const map = JSON.parse(readFileSync(mapPath, 'utf8'))
  const bytes = attribute(js.toString('utf8'), map)
  const totals = new Map()
  bytes.forEach((n, i) => {
    const b = bucket(map.sources[i])
    totals.set(b, (totals.get(b) || 0) + n)
  })
  const sorted = [...totals].sort((a, b) => b[1] - a[1])
  const sum = sorted.reduce((n, [, v]) => n + v, 0) || 1

  console.log('\nwhere the JavaScript comes from (uncompressed, from the source map)')
  for (const [name, n] of sorted.slice(0, 12)) {
    const pct = (n / sum) * 100
    if (pct < 0.4) continue
    const bar = '█'.repeat(Math.max(1, Math.round(pct / 2)))
    console.log(`  ${name.padEnd(20)} ${fmt(kb(n)).padStart(9)}  ${pct.toFixed(1).padStart(5)}%  ${bar}`)
  }
}

const over = rows.filter(([, size, budget]) => size > budget)
if (over.length) {
  console.error(`\n${over.map(([n]) => n).join(', ')} over budget.`)
  console.error('Either find the growth in the table above, or raise the budget in scripts/budget.mjs')
  console.error('deliberately — with a reason, in the commit message.')
  process.exit(1)
}
console.log('\nall within budget.')
